### ISSUE TITLE
LinkedIn Login error.

### ISSUE THREAD

**Issue by emresancaktar** [rubygarage/authorize-me#14] opened 2019-04-17 10:24 UTC
Hey bro,

First of all thanks for the SDK. It's really useful. But there is an error when I want to login with LinkedIn. Console says "Problem with network"

`Authorize.me.on("LinkedIn") { session, error in
      guard let session = session else {
        print("Problem with \(error!)")
        return
      }
      
      print("Authorized with LinkedIn")
      print("Token: \(session.token)")
      print("Username: \(session.user.name)")
    }`

Plist is fine. App opens linkedIn login page when I login to LinkedIn it returns with "[AuthorizeMe] There is bad network response, Problem with network" error.

Any idea ? Thanks.

**Comment by radyslavkrechet** [comment] 2019-04-18 08:29
Hello, thanks a lot!

I've checked it with my LinkedIn developer app and it works. The main problem is that you have no 200 status code of authorization request. So I would suggest you debug your request and response in the file `URLSession+Resuming.swift` of the pod. That how you figure out what the problem is.

I'm closing this issue, but feel free if you need my help again.

**Closed as completed by radyslavkrechet** 2019-04-18 08:29 UTC
Labels: question
